export const AT_POST = {
    IS_LOADING_POSTS : "IS_LOADING_POSTS",
    IS_LOADING_POST : "IS_LOADING_POST",
    READ_POST : "READ_POST",
    READ_POSTS : "READ_POSTS",
    CURRENT_FILTERED_POST : "CURRENT_FILTERED_POST",
    GET_POST_ASSETS : "GET_POST_ASSETS"
}
export const AT_PROFIL = {
    READ_PROFIL : "READ_PROFIL"
}
export const AT_ABOUT = {
    READ_EXPERIENCE_POSTS : "READ_EXPERIENCE_POSTS"
}
export const AT_CONTACT = {
    SEND_CONTACT_FORM_LOADING : "SEND_CONTACT_FORM_LOADING",
    SEND_CONTACT_FORM : "SEND_CONTACT_FORM",
    SEND_CONTACT_FORM_FAILURE : "SEND_CONTACT_FORM_FAILURE"
}

export const AT_UI = {
    ENABLE_BACKTOTOP : "ENABLE_BACKTOTOP"
}

export const AT_GLOBAL = {
    IS_IN_ERROR : "IS_IN_ERROR"
}