export const AT_POST = {
    READ_POST : "READ_POST",
    READ_ALL_POST : "READ_ALL_POST",
    READ_FILTERED_POST : "READ_FILTERED_POST",
    SEND_CURRENT_FILTERED_POST_ID : "SEND_CURRENT_FILTERED_POST_ID",
    GET_POST_ASSETS : "GET_POST_ASSETS"
}
export const AT_PROFIL = {
    READ_PROFIL : "READ_PROFIL"
}
export const AT_ABOUT = {
    READ_EXPERIENCE_POSTS : "READ_EXPERIENCE_POSTS"
}
export const AT_CONTACT = {
    SEND_CONTACT_FORM_LOADING : "SEND_CONTACT_FORM_LOADING",
    SEND_CONTACT_FORM : "SEND_CONTACT_FORM",
    SEND_CONTACT_FORM_FAILURE : "SEND_CONTACT_FORM_FAILURE"
}

export const AT_UI = {
    SEND_HEADER_HEIGHT : "SEND_HEADER_HEIGHT",
    ENABLE_BACKTOTOP : "ENABLE_BACKTOTOP"
}

export const AT_GLOBAL = {
    IS_LOADING : "IS_LOADING",
    IS_IN_ERROR : "IS_IN_ERROR"
}